---
- tags: [graphical, kde]
  block:
    - when: not ((kde and debian) or (kde and archlinux))
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: kde and debian
      block:
        - name: apt install kde + dependencies
          become: true
          ansible.builtin.apt:
            package:
              - sddm
              - kde-plasma-desktop
              - plasma-workspace-wayland
              - pipewire
              - wireplumber
              - pipewire-pulse
              - kscreen
              - dolphin
              - fonts-noto-color-emoji
              - fonts-noto-cjk
              - kwallet-pam
              - kde-spectacle
              - powerdevil

        - name: flatpak install pwvucontrol
          become: true
          community.general.flatpak:
            name: com.saivert.pwvucontrol

    - when: kde and archlinux
      block:
      - name: pacman install kde + dependencies
        become: true
        community.general.pacman:
          name:
            - sddm
            - sddm-kcm
            - plasma-desktop
            - plasma-workspace
            - pipewire
            - wireplumber
            - pipewire-pulse
            - kscreen
            - dolphin
            - noto-fonts-emoji
            - noto-fonts-cjk
            - kwallet-pam
            - spectacle
            - powerdevil

      - name: flatpak install pwvucontrol
        become: true
        community.general.flatpak:
          name: com.saivert.pwvucontrol

    - when: archlinux or debian
      block:
        - name: enable sddm
          become: true
          ansible.builtin.systemd:
            name: sddm
            enabled: true

        - name: run system configuration commands
          become: true
          ansible.builtin.command:
            cmd: "{{dotfiles_path}}/roles/kde/files/root_config.sh"
          changed_when: false

        - name: run configuration commands
          ansible.builtin.command:
            cmd: "{{dotfiles_path}}/roles/kde/files/config.sh"
          changed_when: false
...