---
- name: Download and extract to /usr/local/bin
  become: true
  unarchive:
    src: "https://github.com/tilt-dev/ctlptl/releases/download/v0.5.1/ctlptl.0.5.1.linux.x86_64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
