---
- name: "Install apt packages"
  become: true
  apt:
    state: present 
    pkg:      
      - qemu-kvm 
      - libvirt-daemon-system 
      - libvirt-clients 
      - bridge-utils
    update_cache: true
