- name: install | set facts
  set_fact:
    kind_platform: "{{ansible_system | lower}}"
    kind_architecture: "{{ansible_architecture | lower}}"

- name: install | set architecture
  set_fact: kind_architecture=arm64
  when: kind_architecture == 'aarch64'

- name: install | download url
  become: true
  get_url: url={{url}} dest=/usr/local/bin/kind mode=0755
  vars:
    url: https://github.com/kubernetes-sigs/kind/releases/download/v{{kind_version}}/kind-{{kind_platform}}-{{kind_architecture}}
