---
- tags: [graphical, pulumi]
  block:
    - when: not darwin
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin
      block:
        - name: brew install pulumi
          community.general.homebrew:
            name: pulumi
            path: "{{brew_path}}"
...
