---
- tags: [minimal, pulumi]
  block:
    - when: not (darwin or linux)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: darwin or linux
      block:
        - name: brew install pulumi
          community.general.homebrew:
            name: pulumi
            path: "{{brew_path}}"
...
