---
- name: "Install apt packages"
  become: true
  apt:
    update_cache: true
    state: present 
    pkg:
    - avahi-daemon

- name: "Start avahi-daemon.service"
  become: true
  systemd: 
    name: avahi-daemon
    state: started
    enabled: yes
