---
- tags: [minimal, k9s]
  block:
    - when: not (darwin or linux)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin or linux
      block:
        - name: brew tap derailed/k9s
          community.general.homebrew_tap:
            name: derailed/k9s
            path: "{{brew_path}}"

        - name: brew install derailed/k9s/k9s
          community.general.homebrew:
            name: derailed/k9s/k9s
            path: "{{brew_path}}"
...
