- name: instal | set facts
  set_fact: goland_ide_path=/opt/goland

- name: install | create extract directory
  become: true
  file: path={{goland_ide_path}} state=directory recurse=true mode=0755

- name: install | download url
  become: true
  unarchive: src={{url}} remote_src=true dest={{goland_ide_path}} creates={{goland_ide_path}}/bin/goland.sh extra_opts=--strip-components=1 mode=0755
  vars:
    url: https://download.jetbrains.com/go/goland-{{goland_version}}.tar.gz

- name: install | set java path
  set_fact: goland_java_path={{goland_ide_path}}/jbr
  when: jbr_path is undefined

- name: install | set java path
  set_fact: goland_java_path={{jbr_path}}
  when: jbr_path is not undefined

- name: install | create launch script
  become: true
  copy: content={{content}} dest={{goland_ide_path}}/bin/launch.sh mode=0755
  vars:
    content: "{{lookup('template', 'templates/launch.sh.j2')}}"

- name: install | create desktop launcher
  copy: content={{content}} dest={{user_home}}/.local/share/applications/goland.desktop mode=0755
  vars:
    content: "{{lookup('template', 'templates/desktop.j2')}}"