---
- hosts: all
  roles:
    - asdf
    - asdf-golang
    - asdf-kind
    - asdf-kubectl
    - asdf-nodejs
    - asdf-python
    - asdf-sops
    - asdf-tilt
    - c++
    - clion
    - ctlptl
    - docker
    - git
    - goland
    - gpg
    - oh-my-zsh
    - pycharm
    - qemu
    - vs_code
    - user
