---
- hosts: all
  vars:
    username: "{{ ansible_user_id }}"
  tasks:  
  - fail:
      msg: "directory unset"
    when: "not directory"

  - name: "({{ username }}) Get user information"
    user:
      name: "{{ username }}"
    register: user

  - name: "Install apt packages"
    become: true
    apt:
      state: present 
      pkg:
        - git
      update_cache: true

  - name: "Clone development environment repository"
    become: true
    become_user: "{{ user.name }}"
    git:
      repo: "https://github.com/benfiola/development_environment.git"
      dest: "{{ directory }}"
      update: yes
