---
- name: "Install packages"
  become: true
  apt:
    state: present 
    pkg:
      - vim
      - xclip
      - zsh
      - bash
    update_cache: true

- name: "({{ username }}) Get shell path"
  command:
    cmd: "which {{ shell }}"
  register: shell_path_cmd

- name: "({{ username }}) Get shell path"
  set_fact:
    shell_path: "{{ shell_path_cmd.stdout }}"
  
- name: "({{ username }}) Create/update user"
  become: true
  user:
    name: "{{ username }}"
    state: present
    shell: "{{ shell_path }}"
  register: user

- name: "({{ user.name }}) Get shell profile path"
  vars:
    shell: "{{ user.shell | basename }}"
    shell_map:
      bash: "{{ user.home }}/.bashrc"
      zsh: "{{ user.home }}/.zshrc"
  set_fact:
    shell_profile: "{{ shell_map[shell] }}"
  
- name: "({{ user.name }}) Enable passwordless sudo"
  become: true
  lineinfile:
    path: "/etc/sudoers.d/{{ user.name }}"
    line: '{{ user.name }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: "({{ user.name }}) Create source directory"
  become: true
  become_user: "{{ user.name }}"
  file: 
    path: "{{ user.home }}/source"
    state: "directory"
    recurse: true
    owner: "{{ user.name }}"

- name: "({{ user.name }}) Create/update shell profile"
  become: true
  become_user: "{{ user.name }}"
  blockinfile:
    create: true
    dest: "{{ shell_profile }}"
    block: "{{ lookup('file', 'files/user.zshrc') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ role_name }}"
    owner: "{{ user.name }}"
