---
- name: "Add apt repository GPG keys"
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
  become: true
  
- name: "Add apt repository"
  apt_repository: state=present repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  become: true

- name: "Update apt-cache"
  apt: update_cache=yes
  become: true

- name: "Install apt packages"
  become: true
  apt:
    state: present 
    pkg:
      - docker-ce
  
- name: "Start {{ service }}.service"
  become: true
  systemd: name={{ service }} state=started enabled=yes
  vars:
    service: docker