---
- name: Install docker
  block:
  - name: Add GPG key {{key_url}}
    apt_key: url={{key_url}} state=present
    become: true

  - name: Add repository {{repository}}
    apt_repository: state=present repo={{repository}}
    become: true

  - name: Update apt-cache
    apt: update_cache=yes
    become: true

  - name: Install packages via apt
    apt: name={{item}} state=present
    become: true
    loop:
      - docker-ce

  - name: Start service
    systemd: name=docker state=started enabled=yes
  
  vars:
    key_url: https://download.docker.com/linux/ubuntu/gpg
    repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
