---
- name: Install Google Chrome
  block:
    - name: Check if {{dpkg_name}} is installed
      shell: dpkg -s {{dpkg_name}}
      register: package_search
      failed_when: package_search.rc not in [0, 1]

    - block:
      - name: Download {{download_url}} to {{download_path}}
        get_url: url={{download_url}} dest={{download_path}}

      - name: Install packages via apt
        apt: name={{item}} state=present
        become: true
        loop:
          - gdebi-core

      - name: Install {{download_path}} via apt
        apt: deb={{download_path}}
        become: true
      when: package_search.rc == 1
  
  always:
    - name: Remove {{download_path}}
      file: path={{download_path}} state=absent
  
  vars:
    download_url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    download_path: /tmp/google_chrome.deb
    dpkg_name: google-chrome-stable
