---
- name: Install kubernetes
  block:
    - block:
      - name: Obtaining version from {{kubectl_version_url}}
        uri: url={{kubectl_version_url}} return_content=yes
        register: kubectl_version_response
      - set_fact: kubectl_version={{kubectl_version_response.content | replace('\n', '')}}
      - set_fact: kubectl_url={{kubectl_url_template | replace('{version}', kubectl_version)}}

      - name: Download {{kubectl_url}} to {{kubectl_install_path}}
        get_url: url={{kubectl_url}} dest={{kubectl_install_path}} mode=0755
        become: true
      when: kubectl_install_path is not exists
    
    - block:
      - name: Download {{minikube_url}} to {{minikube_install_path}}
        get_url: url={{minikube_url}} dest={{minikube_install_path}} mode=0755
        become: true
      when: minikube_install_path is not exists
  
  vars:
    kubectl_version_url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    kubectl_url_template: https://storage.googleapis.com/kubernetes-release/release/{version}/bin/linux/amd64/kubectl
    minikube_url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    kubectl_install_path: /usr/local/bin/kubectl
    minikube_install_path: /usr/local/bin/minikube
  