---
# - import_tasks: clion.yml
# - import_tasks: cplusplus.yml
# - import_tasks: docker.yml
# - import_tasks: git.yml
# - import_tasks: google_chrome.yml
# - import_tasks: kubernetes.yml
# - import_tasks: mdns.yml
# - import_tasks: nodenv.yml
# - import_tasks: pycharm.yml
# - import_tasks: pyenv.yml
# - import_tasks: qemu.yml
# - import_tasks: zsh.yml
# - import_tasks: user.yml
# - import_tasks: spotify.yml
- import_tasks: unity.yml
