---
- name: Install nodenv
  block:
  - import_tasks: git.yml
  - import_tasks: user.yml
  - import_tasks: zsh.yml
  
  - name: Check if {{install_path}} contains files
    find: paths={{install_path}}
    register: installed_files
  
  - block:
    - name: Create {{install_path}}
      file: path={{install_path}} state=directory mode=0777
      become: true

    - name: Clone {{nodenv_url}} -> {{install_path}}
      git: repo={{nodenv_url}} dest={{install_path}}
    
    - name: Clone {{nodenv_build_url}} -> {{install_path}}/plugins/nodenv-build
      git: repo={{nodenv_build_url}} dest={{install_path}}/plugins/nodenv-build
    when: installed_files.matched == 0
  
  - name: Write block to {{profile_path}}
    blockinfile:
      path: "{{profile_path}}"
      state: present
      marker: "# {mark} nodenv"
      block: |
        export NODENV_ROOT={{install_path}}
        export PATH=$NODENV_ROOT/bin:$PATH
        eval "$(nodenv init -)"
        export PATH=node_modules/.bin:$PATH
    become: true 
    
  vars:
    install_path: /opt/nodenv
    nodenv_url: https://github.com/nodenv/nodenv.git
    nodenv_build_url: https://github.com/nodenv/node-build
    profile_path: /home/{{user}}/.zshrc
