---
- name: Install oh-my-zsh

  block:
    - import_tasks: user.yml
    - import_tasks: zsh.yml

    - block:
      - name: Download {{download_url}} to {{download_path}}
        get_url: url={{download_url}} dest={{download_path}} mode=0755
      
      - name: "Run {{download_path}}"
        command: "{{download_path}}"
        become: true
        become_user: "{{user}}"
      when: install_path is not exists

  always:
    - name: Remove {{download_path}}
      file: path={{download_path}} state=absent
    
  vars:
    download_url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    download_path: /tmp/oh-my-zsh.sh
    install_path: /home/{{user}}/.oh-my-zsh

