---
- name: Install Pycharm

  block:
    - import_tasks: user.yml

    - name: Check if {{install_path}} contains files
      find: paths={{install_path}}
      register: installed_files

    - block:
      - name: Download {{url}} to {{download_path}}
        get_url: url={{url}} dest={{download_path}}

      - name: Create {{install_path}}
        file: path={{install_path}} mode=0777 state=directory
        become: true
      
      - name: Create {{desktop_file}}
        file: path={{desktop_file}} state=touch owner={{user}} group={{user}}
        become: true
      
      - name: Write {{desktop_file}}
        blockinfile: 
          path: "{{desktop_file}}"
          state: present
          block: |
            [Desktop Entry]
            Version=1.0
            Type=Application
            Name=PyCharm
            Icon={{install_path}}/bin/pycharm.png
            Exec="{{install_path}}/bin/pycharm.sh" %f
            Comment=The Drive to Develop
            Categories=Development;IDE;
            Terminal=false
            StartupWMClass=pycharm
        become: true
        
      - name: Extract {{download_path}} to {{install_path}}
        unarchive: src={{download_path}} dest={{install_path}} remote_src=yes extra_opts=--strip-components=1
      when: installed_files.matched == 0

  always:
    - name: Remove {{download_path}}
      file: path={{download_path}} state=absent

  vars:
    desktop_file: /home/{{user}}/.local/share/applications/pycharm.desktop
    install_path: /opt/pycharm
    download_path: /tmp/pycharm.tar.gz
    url: https://download.jetbrains.com/python/pycharm-professional-2019.3.1.tar.gz

