---
- name: Install qemu

  block:
    - name: Install packages via apt
      apt: name={{item}} state=present
      become: true
      loop:
        - qemu-kvm 
        - libvirt-daemon-system 
        - libvirt-clients 
        - bridge-utils
