---
- name: Install spotify
  block:
  - name: Add GPG key {{key_url}}
    apt_key: url={{key_url}} state=present
    become: true

  - name: Add repository {{repository}}
    apt_repository: state=present repo={{repository}}
    become: true

  - name: Update apt-cache
    apt: update_cache=yes
    become: true

  - name: Install packages via apt
    apt: name={{item}} state=present
    become: true
    loop:
      - spotify-client  
  vars:
    key_url: https://download.spotify.com/debian/pubkey.gpg
    repository: deb http://repository.spotify.com stable non-free
