---
- name: Install Unity

  block:
    - import_tasks: user.yml

    - name: Create {{install_folder}}
      file: path={{install_folder}} mode=0777 state=directory
      become: true

    - name: Copy {{icon_filename}} -> {{icon_path}}
      copy: src={{icon_filename}} dest={{icon_path}}
    
    - name: Create {{desktop_file}}
      file: path={{desktop_file}} state=touch owner={{user}} group={{user}}
      become: true  
        
    - name: Write {{desktop_file}}
      blockinfile: 
        path: "{{desktop_file}}"
        state: present
        block: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Unity Hub
          Icon={{icon_path}}
          Exec="{{install_path}}" %f
          Comment=
          Categories=Development;IDE;
          Terminal=false
          StartupWMClass=unityhub
      become: true
    
    - name: Download {{url}} to {{install_path}}
      get_url: url={{url}} dest={{install_path}} mode=0755
  when: install_path is not exists

  vars:
    desktop_file: /home/{{user}}/.local/share/applications/unity.desktop
    install_folder: /opt/unity
    url: https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage

    icon_filename: icon_unityhub.png
    icon_path: "{{install_folder}}/{{icon_filename}}"
    
    install_filename: UnityHub.AppImage
    install_path: "{{install_folder}}/{{install_filename}}"
