---
- name: Create user

  block:
    - name: Create user {{user}}
      user: name={{user}} password={{'password'|password_hash('sha512', 'salt')}} create_home=yes state=present
      become: true

    - name: Create {{sudoers_file}}
      file: path={{sudoers_file}} mode=0440 state=touch
      become: true 
    
    - name: Write {{sudoers_file}}
      blockinfile:
        path: "{{sudoers_file}}"
        block: |
          {{user}} ALL=(ALL) NOPASSWD: ALL
      become: true 
  
  vars:
    sudoers_file: /etc/sudoers.d/{{user}}
