---
- name: Install zsh

  block:
    - import_tasks: user.yml

    - name: Install packages via apt
      apt: name={{item}} state=present
      become: true
      loop:
        - zsh
    
    - name: "Update {{user}} shell to zsh"
      user: name={{user}} shell=/usr/bin/zsh
      become: true

    - name: "Creating {{zshrc}}"
      file: path={{zshrc}} state=touch owner={{user}} group={{user}} mode=0664
      become: true
    
  vars:
    home: "/home/{{user}}"
    zshrc: "{{home}}/.zshrc"
