- name: instal | set facts
  set_fact: pycharm_ide_path=/opt/pycharm

- name: install | create extract directory
  become: true
  file: path={{pycharm_ide_path}} state=directory recurse=true mode=0755

- name: install | download url
  become: true
  unarchive: src={{url}} remote_src=true dest={{pycharm_ide_path}} creates={{pycharm_ide_path}}/bin/pycharm.sh extra_opts=--strip-components=1 mode=0755
  vars:
    url: https://download.jetbrains.com/python/pycharm-professional-{{pycharm_version}}.tar.gz

- name: install | set java path
  set_fact: pycharm_java_path={{pycharm_ide_path}}/jbr
  when: jbr_path is undefined

- name: install | set java path
  set_fact: pycharm_java_path={{jbr_path}}
  when: jbr_path is not undefined

- name: install | create launch script
  become: true
  copy: content={{content}} dest={{pycharm_ide_path}}/bin/launch.sh mode=0755
  vars:
    content: "{{lookup('template', 'templates/launch.sh.j2')}}"

- name: install | create desktop launcher
  copy: content={{content}} dest={{user_home}}/.local/share/applications/pycharm-professional.desktop mode=0755
  vars:
    content: "{{lookup('template', 'templates/desktop.j2')}}"