---
- tags: [minimal, "{{role_name}}"]
  block:
    - when: not true
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: true
      block:
        - name: install asdf-kubectl
          benfiola.dotfiles.asdf_plugin:
            name: kubectl
...