---
- tags: [graphical, alfred]
  block:
    - when: not darwin
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin
      block:
        - name: brew cask install alfred
          community.general.homebrew_cask:
            name: alfred
            path: "{{brew_path}}"
...
