- name: install asdf dependencies with apt
  when: debian
  become: true
  ansible.builtin.apt:
    package:
      - curl
      - git

- name: install asdf dependencies with pacman
  when: archlinux
  become: true
  community.general.pacman:
    name:
      - curl
      - git

- name: clone asdf repo
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{user.home}}/.asdf"

- name: create asdf .tool-versions file
  ansible.builtin.file:
    path: "{{user.home}}/.tool-versions"
    state: touch
    modification_time: preserve
    access_time: preserve
