- name: install c dependencies with apt
  become: true
  when: debian
  ansible.builtin.apt:
    package:
      - cmake
      - libc-dev
      - libc++-dev
      - gcc
      - g++
      - make

- name: install c dependencies with pacman
  become: true
  when: archlinux
  community.general.pacman:
    name:
      - cmake
      - gcc
      - glibc
      - libc++
      - make
  
- name: install c dependencies with brew
  when: darwin
  community.general.homebrew:
    name:
      - cmake
    path: "{{brew_path}}"
