- when: darwin
  block:
    - name: install google-chrome with dmg
      ansible.builtin.include_tasks: ./helpers/install-app-dmg.yaml
      vars:
        url: https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg
        app: Google Chrome.app

    - name: remove existing google-chrome policy
      become: true
      failed_when: false
      ansible.builtin.command:
        cmd: profiles -R -F {{dotfiles_path}}/chromium/macos.mobileconfig

    - name: install google-chrome policy
      ansible.builtin.command:
        cmd: open {{dotfiles_path}}/chromium/macos.mobileconfig

- when: linux
  block:
    - name: install chromium with flatpak
      become: true
      community.general.flatpak:
        name: org.chromium.Chromium

    - block:
      - name: create chromium policy folder
        become: true
        ansible.builtin.file:
          path: "{{file|dirname}}"
          recurse: true
          state: directory

      - name: install chromium policy
        become: true
        ansible.builtin.file:
          src: "{{dotfiles_path}}/chromium/policy.json"
          dest: "{{file}}"
          state: hard
      vars:
        file: /etc/chromium-browser/policies/managed/policy.json
    
    - block:
        - name: create flatpak extension folder
          become: true
          ansible.builtin.file:
            path: "{{folder|dirname}}"
            recurse: true
            state: directory

        - name: symlink chromium policies to flatpak extension folder
          become: true
          ansible.builtin.file:
            src: "/etc/chromium-browser"
            path: "{{folder}}"
            state: link
      vars:
        folders:
          amd64: /var/lib/flatpak/extension/org.chromium.Chromium.Extension.system-policies/x86_64/1
          arm64: /var/lib/flatpak/extension/org.chromium.Chromium.Extension.system-policies/aarch64/1
        folder: "{{folders[architecture]}}"
