- name: install flatpak with apt
  become: true
  when: debian
  ansible.builtin.apt:
    package:
      - flatpak
    
- name: install flatpak with pacman
  when: archlinux
  become: true
  community.general.pacman:
    name:
      - flatpak

- name: add flathub repo
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
