- name: find fonts
  ansible.builtin.find:
    paths: "{{dotfiles_path}}/fonts"
    patterns: "*.ttf"
  register: fonts

- name: install fonts
  block:
    - name: create font directory
      become: true
      ansible.builtin.file:
        path: "{{directory}}"
        recurse: true
        state: directory
      
    - name: install fonts
      become: true
      ansible.builtin.file:
        src: "{{item}}"
        dest: "{{directory}}/{{item | basename}}"
        state: hard
      loop: "{{fonts.files | map(attribute='path') }}"
  vars:
    directories:
      linux: /usr/local/share/fonts
      darwin: /Library/Fonts
    directory: "{{directories[system]}}"
