- when: linux and gnome
  block:
    - name: install gnome-terminal with apt
      become: true
      when: debian
      ansible.builtin.apt:
        package:
          - gnome-terminal
      
    - name: install gnome-terminal with pacman
      become: true
      when: archlinux
      community.general.pacman:
        name:
          - gnome-terminal

    - name: run configuration commands
      ansible.builtin.command:
        cmd: "{{item}}"
      loop:
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ audible-bell true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ background-color '#2E3440'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ background-transparency-percent 50
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ backspace-binding 'ascii-delete'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ bold-color '#D8DEE9'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ bold-color-same-as-fg true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ bold-is-bright false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ cell-height-scale 1.0
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ cell-width-scale 1.0
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ cjk-utf8-ambiguous-width 'narrow'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ cursor-background-color 'rgb(216,222,233)'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ cursor-blink-mode 'system'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ cursor-colors-set true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ cursor-foreground-color 'rgb(59,66,82)'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ cursor-shape 'block'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ custom-command ''
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ default-size-columns 80
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ default-size-rows 24
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ delete-binding 'delete-sequence'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ enable-bidi true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ enable-shaping true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ enable-sixel false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ encoding 'UTF-8'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ exit-action 'close'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ font 'Monospace 12'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ foreground-color '#D8DEE9'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ highlight-background-color 'rgb(136,192,208)'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ highlight-colors-set true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ highlight-foreground-color 'rgb(46,52,64)'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ login-shell false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ palette "['#3B4252', '#BF616A', '#A3BE8C', '#EBCB8B', '#81A1C1', '#B48EAD', '#88C0D0', '#E5E9F0', '#4C566A', '#BF616A', '#A3BE8C', '#EBCB8B', '#81A1C1', '#B48EAD', '#8FBCBB', '#ECEFF4']"
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ preserve-working-directory 'safe'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ rewrap-on-resize true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ scroll-on-keystroke true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ scroll-on-output false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ scrollback-lines 10000
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ scrollback-unlimited false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ scrollbar-policy 'always'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ text-blink-mode 'always'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ use-custom-command false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ use-system-font true
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ use-theme-colors false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ use-theme-transparency false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ use-transparent-background false
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ visible-name 'Nord'
        - gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:422b29ae-8085-4eb4-9051-e9e81c408fd6/ word-char-exceptions '@ms nothing'
        - gsettings set org.gnome.Terminal.ProfilesList list "['422b29ae-8085-4eb4-9051-e9e81c408fd6']"
        - gsettings set org.gnome.Terminal.ProfilesList default '422b29ae-8085-4eb4-9051-e9e81c408fd6'
