- when: linux and gnome
  block:
    - name: install gnome with apt
      become: true
      when: debian
      ansible.builtin.apt:
        package:
          - gdm3
          - gnome-shell
          - gnome-shell-extensions
          - gnome-session
          - gnome-themes-extra
          - gnome-tweaks
          - gnome-control-center
          - nautilus
          - fonts-cantarell
          - adwaita-icon-theme-full

    - name: install gnome with pacman
      become: true
      when: archlinux
      community.general.pacman:
        name:
          - gdm
          - gnome-shell
          - gnome-shell-extensions
          - gnome-session
          - gnome-themes-extra
          - gnome-tweaks
          - gnome-control-center
          - nautilus
          - cantarell-fonts
          - adwaita-icon-theme

    - name: enable gdm
      become: true
      ansible.builtin.systemd:
        name: gdm
        enabled: true

    - name: run configuration commands
      ansible.builtin.command:
        cmd: "{{item}}"
      loop:
        - gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
        - gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
        - gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
        - gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
        - gsettings set org.gnome.desktop.interface monospace-font-name 'FiraCode Nerd Font Mono 12'
        - gsettings set org.gnome.desktop.wm.preferences theme 'Adwaita-dark'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/ulauncher-toggle/']"
