- name: install golang build dependencies with apt
  when: debian
  become: true
  ansible.builtin.apt:
    package:
      - curl
      - coreutils

- name: install golang build dependencies with pacman
  when: archlinux
  become: true
  community.general.pacman:
    name:
      - curl
      - coreutils
  
- name: install asdf-golang
  asdf_plugin:
    name: golang
