- when: darwin
  block:
    - name: install iTerm2.app
      become: true
      ansible.builtin.unarchive:
        src: https://iterm2.com/downloads/stable/iTerm2-3_4_16.zip
        remote_src: true
        dest: /Applications
        creates: /Applications/iTerm.app

    - name: run configuration commands
      ansible.builtin.command:
        cmd: "{{item}}"
      loop:
        - defaults write com.googlecode.iterm2 PrefsCustomFolder -string "{{dotfiles_path}}/iterm/com.googlecode.iterm2.plist"
        - defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
