- name: install java build dependencies with apt
  when: debian
  become: true
  ansible.builtin.apt:
    package:
      - bash
      - curl
      - coreutils
      - unzip
      - jq

- name: install java build dependencies with pacman
  when: archlinux
  become: true
  community.general.pacman:
    name:
      - bash
      - curl
      - coreutils
      - unzip
      - jq
  
- name: install asdf-java
  asdf_plugin:
    name: java
