- when: linux and kde
  block:
    - name: install kde with apt
      become: true
      when: debian
      ansible.builtin.apt:
        package:
          - sddm
          - kde-plasma-desktop
          - plasma-workspace-wayland
          - pulseaudio
          - pavucontrol
          - plasma-pa
          - kscreen
          - dolphin
          - fonts-noto-color-emoji

    - name: install kde with pacman
      become: true
      when: archlinux
      community.general.pacman:
        name:
          - sddm
          - plasma-desktop
          - plasma-wayland-session
          - pulseaudio
          - pavucontrol
          - plasma-pa
          - kscreen
          - dolphin
          - noto-fonts-emoji

    - name: enable sddm
      become: true
      ansible.builtin.systemd:
        name: sddm
        enabled: true

    - name: run configuration commands
      ansible.builtin.command:
        cmd: "{{item}}"
      loop:
        - env QT_QPA_PLATFORM=offscreen lookandfeeltool -a org.kde.breezedark.desktop
        - gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
        - gsettings set org.gnome.desktop.interface gtk-theme 'Breeze-Dark'
        - gsettings set org.gnome.desktop.interface icon-theme 'breeze-dark'
        - gsettings set org.gnome.desktop.interface cursor-theme 'breeze_cursors'
        - gsettings set org.gnome.desktop.interface monospace-font-name 'FiraCode Nerd Font Mono 12'
