- when: linux and kde
  block:
    - name: install kde with apt
      become: true
      when: debian
      ansible.builtin.apt:
        package:
          - sddm
          - kde-plasma-desktop
          - plasma-workspace-wayland

    - name: install kde with pacman
      become: true
      when: archlinux
      community.general.pacman:
        name:
          - gdm
          - gnome-shell
          - gnome-shell-extensions
          - gnome-session
          - gnome-themes-extra
          - gnome-tweaks
          - gnome-control-center
          - nautilus
          - cantarell-fonts
          - adwaita-icon-theme

    - name: enable sddm
      become: true
      ansible.builtin.systemd:
        name: sddm
        enabled: true

    - name: run kde configuration script
        ansible.builtin.command:
          cmd: "{{dotfiles_path}}/kde/lookandfeel.sh"
