- name: install open-vm-tools with apt
  become: true
  when: debian and vm
  ansible.builtin.apt:
    package:
      - open-vm-tools
      - open-vm-tools-desktop

- when: archlinux and amd64 and vm
  block:
    - name: install open-vm-tools with pacman
      become: true
      community.general.pacman:
        name:
          - open-vm-tools
    
    - name: start and enable open-vm-tools services
      become: true
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
        enabled: true
      loop:
        - vmtoolsd 
        - vmware-vmblock-fuse