
- when: darwin
  block:
    - name: set brew path fact
      ansible.builtin.set_fact:
        brew_path: "{{path}}"
      vars:
        paths:
          amd64: /usr/local/bin
          arm64: /opt/homebrew/bin
        path: "{{paths[architecture]}}"
      
    - name: install brew with script
      ansible.builtin.include_tasks: ./helpers/install-script.yaml
      vars:        
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        binary: "{{brew_path}}"

- when: debian
  block:
    - name: update apt cache
      become: true
      changed_when: false
      ansible.builtin.apt:
        update_cache: true

    - name: remove unattended upgrades with apt
      become: true
      ansible.builtin.apt:
        package:
          - unattended-upgrades
        state: absent
        
- name: update pacman cache
  when: archlinux
  become: true
  community.general.pacman:
    update_cache: true
