- name: enable passwordless sudo
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/99-{{user.name}}
    create: true
    line: "{{user.name}} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
