- name: install snapd with apt
  become: true
  when: debian
  ansible.builtin.apt:
    package:
      - snapd
    
- when: archlinux
  block:
    - name: install snapd with AUR
      ansible.builtin.include_tasks: ./helpers/install-aur.yaml
      vars:
        url: https://aur.archlinux.org/snapd.git
        package: snapd
    
    - name: enable snapd socket
      become: true
      ansible.builtin.systemd:
        name: snapd.socket
        state: started
        enabled: true
    
    - name: symlink snapd to /snapd
      become: true
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        path: /snap
        state: link
