- name: install starship with script
  ansible.builtin.include_tasks: ./helpers/install-script.yaml
  vars:
    url: https://raw.githubusercontent.com/starship/starship/v1.10.3/install/install.sh
    binary: /usr/local/bin/starship
    args: --yes
    become: true

- name: create starship prompt configuration directory
  ansible.builtin.file:
    path: "{{user.home}}/.config"
    recurse: true
    state: directory

- name: install starship prompt configuration
  ansible.builtin.file:
    src: "{{dotfiles_path}}/starship/starship.toml"
    dest: "{{user.home}}/.config/starship.toml"
    state: link
