- name: install protonqt-up with flatpak
  when: linux
  become: true
  community.general.flatpak:
    name: net.davidotek.pupgui2

- name: install steam debian
  when: debian
  fail:
    msg: unimplemented

- name: install steam darwin
  when: darwin
  fail:
    msg: unimplemented

- name: install steam with pacman
  become: true
  when: archlinux
  community.general.pacman:
    name:
      - steam
