- when: linux
  block:
    - when: debian
      block:
        - name: install ulauncher dependencies with apt
          become: true
          ansible.builtin.apt:
            package:
              - wmctrl

        - name: install ulauncher with apt
          become: true
          ansible.builtin.apt:
            deb: https://github.com/Ulauncher/Ulauncher/releases/download/5.15.0/ulauncher_5.15.0_all.deb

    - name: install ulauncher with AUR
      when: archlinux
      ansible.builtin.include_tasks: ./helpers/install-aur.yaml
      vars:
        url: https://aur.archlinux.org/ulauncher.git
        package: ulauncher
    
    - name: create ulauncher-toggle.desktop
      become: true
      ansible.builtin.template:
        src: desktop.j2
        dest: /usr/share/applications/{{name}}.desktop
        mode: '0644'
      vars:
        command: ulauncher-toggle
        name: ulauncher-toggle
    
    - block:
      - name: create ulauncher user theme directory
        ansible.builtin.file:
          path: "{{folder}}/user-themes"
          state: directory
          recurse: true

      - name: install ulauncher theme
        ansible.builtin.file:
          src: "{{dotfiles_path}}/ulauncher/theme"
          dest: "{{folder}}/user-themes/theme"
          state: link

      - name: install ulauncher configuration
        ansible.builtin.file:
          src: "{{dotfiles_path}}/ulauncher/settings.json"
          dest: "{{folder}}/settings.json"
          state: link
      vars:
        folder: "{{user.home}}/.config/ulauncher"

    - name: install ulauncher keybindings
      when: gnome
      ansible.builtin.command:
        cmd: "{{item}}"
      loop:
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/ulauncher-toggle/ binding '<Primary>space'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/ulauncher-toggle/ command 'ulauncher-toggle'
        - gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/ulauncher-toggle/ name 'ulauncher-toggle'

    - name: install ulauncher keybindings
      when: kde
      ansible.builtin.command:
        cmd: "{{item}}"
      loop:
        - kwriteconfig5 --file "{{user.home}}/.config/kglobalshortcutsrc" --group ulauncher-toggle.desktop --key _launch "Ctrl+Space,none,ulauncher-toggle"
        - kwriteconfig5 --file "{{user.home}}/.config/kglobalshortcutsrc" --group ulauncher-toggle.desktop --key _k_friendly_name "ulauncher-toggle"
    
    - name: start ulauncher systemd service
      ansible.builtin.systemd:
        name: ulauncher
        scope: user
        state: started
        enabled: true
