- when: debian
  block:
    - name: add variety ppa
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:variety/stable

    - name: install variety
      become: true
      ansible.builtin.apt:
        update_cache: true
        package:
          - variety
  
- name: install variety with pacman
  become: true
  when: archlinux
  community.general.pacman:
    name:
      - variety

- when: linux
  block:
    - block:
      - name: create variety configuration folder
        ansible.builtin.file:
          path: "{{folder}}"
          recurse: true
          state: directory

      - name: create variety first-run file
        ansible.builtin.shell:
          cmd: date > {{folder}}/.firstrun
          creates: "{{folder}}/.firstrun"

      - name: install variety configuration
        ansible.builtin.file:
          src: "{{dotfiles_path}}/variety/variety.conf"
          dest: "{{folder}}/variety.conf"
          state: link
      vars:
        folder: "{{user.home}}/.config/variety"

    - when: linux
      block:
        - name: install variety systemd service unit file
          become: true
          ansible.builtin.template:
            src: systemd.service.j2
            dest: /usr/lib/systemd/user/variety.service
          vars:
            description: variety
            command: /usr/bin/variety --profile %h/.config/variety/

        - name: start variety systemd service
          ansible.builtin.systemd:
            name: variety
            scope: user
            state: started
            enabled: true