- name: install vscode with apt
  become: true
  when: debian
  ansible.builtin.apt:
    deb: "{{url}}"
  vars:
    urls:
      amd64: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      arm64: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64
    url: "{{urls[architecture]}}"

- name: install vscode with aur
  when: archlinux
  ansible.builtin.include_tasks: ./helpers/install-aur.yaml
  vars:
    url: https://aur.archlinux.org/visual-studio-code-bin.git
    package: visual-studio-code-bin
    
- name: install vscode with zip
  when: darwin
  ansible.builtin.unarchive:
    src: https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal
    remote_src: true
    dest: /Applications
    creates: /Applications/Visual Studio Code.app