- name: install | set facts
  set_fact:
    vscode_os_family: "{{ansible_os_family | lower}}"
    vscode_architecture: "{{ansible_architecture | lower}}"

- name: install | set architecture
  set_fact: vscode_architecture=arm64
  when: vscode_architecture == 'aarch64'
  
- name: install | install deb
  become: true
  apt: deb={{url}} state=present
  vars:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-{{vscode_architecture}}
  when: vscode_os_family == 'debian'
