- name: install | install apt packages
  become: true
  apt: pkg=git state=present
  
- name: install | clone repository
  become: true
  become_user: "{{user_name}}"
  git: repo={{repo}} dest={{ohmyzsh_path}}
  vars:
    repo: https://github.com/ohmyzsh/ohmyzsh.git

- name: install | create theme
  become: true
  become_user: "{{user_name}}"
  copy: content={{content}} dest={{dest}} remote_src=true
  vars:
    content: "{{lookup('template', 'templates/theme.j2')}}"
    dest: "{{ohmyzsh_path}}/custom/themes/theme.zsh-theme"

- name: install | update profile
  become: true
  become_user: "{{user_name}}"
  blockinfile: dest={{user_profile}} block={{block}} marker={{marker}} create=true
  vars:
    block: "{{lookup('template', 'templates/profile.j2')}}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{role_name}}"
