---
- block:
  - name: get asdf plugin list
    command: 
      cmd: "{{ executable }} plugin list"
    register: asdf_plugin_list


  - name: Install asdf-{{ plugin }}
    become: true
    become_user: "{{ user }}"
    command:
      cmd: "{{ executable }} plugin add {{ plugin }}"
    when: "plugin not in asdf_plugin_list.stdout"
  vars:
    executable: "{{ asdf_path }}/bin/asdf"
    plugin: kubectl
  