---
- block:
  - name: "Update apt-cache"
    apt: update_cache=yes
    become: true

  - name: "Install apt packages"
    become: true
    apt:
      state: present 
      pkg:
        - vim
        - zsh
        - xclip

  - name: "Set '{{ user }}' shell to {{ shell }}"
    user: name={{ user }} state=present shell={{ shell }}
    become: true

  - name: "Create {{ path }} to add {{ user }} to sudoers"
    become: true
    lineinfile:
      path: "{{ path }}"
      line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
    vars:
      path: "/etc/sudoers.d/{{ user }}"

  - name: "Create {{ path }}"
    file: path={{ path }} state=directory recurse=true owner={{ user }}
    become: true
    become_user: "{{ user }}"
    vars:
      path: "{{ user_home }}/source"

  - name: "Create {{ oh_my_zsh_path }}"
    file: path={{ oh_my_zsh_path }} state=directory recurse=true owner={{ user }}
    become: true
    become_user: "{{ user }}"

  - name: "Clone {{ oh_my_zsh_url }} to {{ oh_my_zsh_path }}"
    git: repo={{ oh_my_zsh_url }} dest={{ oh_my_zsh_path }}
    become: true
    become_user: "{{ user }}"


  - name: "Copy {{ source }} to {{ destination }}"
    copy: src={{ source }} dest={{ destination }} owner={{ user }}
    become: true
    become_user: "{{ user }}"
    vars:
      source: "files/ben.zsh-theme"
      destination: "{{ oh_my_zsh_path }}/custom/themes/ben.zsh-theme"

  - name: "Create {{ shell_profile }}"
    file: path={{ shell_profile }} state=touch owner={{ user }}
    become: true
    become_user: "{{ user }}"

  - name: "Add {{ item }} to {{ shell_profile }}"
    blockinfile:
      dest: "{{ shell_profile }}"
      block: "{{ lookup('file', '{{ item }}') }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ role_name }}:{{ item }}"
    vars:
      file: files/ohmyzsh.zshrc
    with_items:
      - files/ohmyzsh.zshrc
      - files/aliases.zshrc

  - name: "Add {{ item }} to {{ shell_profile }}"
    blockinfile:
      dest: "{{ shell_profile }}"
      block: "{{ lookup('template', '{{ item }}') }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ role_name }}:{{ item }}"
    vars:
      file: files/ohmyzsh.zshrc
    with_items:
      - templates/ohmyzsh.zshrc.j2

  - name: "Set facts"
    set_fact:
      user: "{{ user }}"
      user_home: "{{ user_home }}"
      shell: "{{ shell }}"
      shell_profile: "{{ shell_profile }}"
  vars:
    user: "{{ user }}"
    user_home: "{{ user_home }}"
    shell: "{{ shell }}"
    shell_profile: "{{ shell_profile }}"
    oh_my_zsh_url: "https://github.com/ohmyzsh/ohmyzsh.git"
    oh_my_zsh_path: "{{ oh_my_zsh_path }}"
