- name: install | install apt packages
  become: true
  apt: pkg=make,build-essential,libssl-dev,zlib1g-dev,libbz2-dev,libreadline-dev,libsqlite3-dev,wget,curl,llvm,libncursesw5-dev,xz-utils,tk-dev,libxml2-dev,libxmlsec1-dev,libffi-dev,liblzma-dev state=present

- name: install | install asdf plugin + version
  become: true
  become_user: "{{user_name}}"
  asdf: plugin=python version={{python_version}} state=present executable={{asdf_executable}} global_=true

  