---
- block:
  - name: get asdf plugin list
    command: 
      cmd: "{{ executable }} plugin list"
    register: asdf_plugin_list

  - name: Install asdf-{{ plugin }}
    become: true
    become_user: "{{ user }}"
    command:
      cmd: "{{ executable }} plugin add {{ plugin }}"
    when: "plugin not in asdf_plugin_list.stdout"
  
  - name: Install python build dependencies
    become: true
    apt:
      state: present 
      pkg:
      - make
      - build-essential
      - libssl-dev 
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
  vars:
    executable: "{{ asdf_path }}/bin/asdf"
    plugin: python