---
- tags: [graphical]
  block:
    - when: not darwin
      block:
        - name: unimplemented
          empty: {}
    
    - when: darwin
      block:
        - name: run configuration script
          ansible.builtin.command:
            cmd: "{{dotfiles_path}}/roles/macos/files/config.sh"
...