---
- tags: [optional, whatsapp]
  block:
    - when: not (darwin)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin
      block:
        - name: brew cask install whatsapp
          community.general.homebrew_cask:
            name: whatsapp
            path: "{{brew_path}}"
...