---
- name: install stormssh python dependency
  pip:
    name: stormssh

- name: ensure .ssh folder exists
  ansible.builtin.file:
    path: "{{user.home}}/.ssh"
    state: directory

- name: generate {{ssh_user}}.{{ssh_host}} keypair
  community.crypto.openssh_keypair:
    path: "{{user.home}}/.ssh/{{ssh_user}}.{{ssh_host}}"
    size: 2048

- name: add {{ssh_user}}.{{ssh_host}} ssh config
  vars:
    groups:
      darwin: "staff"
    group: "{{groups.get(os_family, omit)}}"
  community.general.ssh_config:
    host: "{{ssh_user}}.{{ssh_host}}"
    hostname: "{{ssh_host}}"
    identity_file: "{{user.home}}/.ssh/{{ssh_user}}.{{ssh_host}}"
    state: present
    user: "{{user.name}}"
    group: "{{group}}"
...
