---
- tags: [minimal]
  block:
    - when: not true
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: true
      block:
        - name: create {{ssh_user}}@{{ssh_host}} key
          vars:
            ssh_user: benfiola
            ssh_host: github.com
          ansible.builtin.include_role: 
            role: ssh
            tasks_from: create-ssh-key.yaml
          with_items:
            - {ssh_user: benfiola, ssh_host: github.com}
...
