---
- tags: [minimal, ssh]
  block:
    - when: not true
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: true
      block:
        - name: create ssh config
          vars:
            ssh_host: "{{ssh_item.ssh_host | default(omit)}}"
            ssh_hostname: "{{ssh_item.ssh_hostname}}"
          ansible.builtin.include_role:
            name: benfiola.dotfiles.utils
            tasks_from: create-ssh-config.yaml
          loop:
            - {ssh_host: benfiola.github.com, ssh_hostname: github.com}
          loop_control:
            label: "{{ssh_host}}"
            loop_var: ssh_item
...
