---
- tags: [minimal, ssh]
  block:
    - when: not true
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: true
      block:
        - name: create ssh config
          vars:
            opensc_lib:
              darwin: /usr/local/lib/opensc-pkcs11.so
              linux: /usr/lib/opensc-pkcs11.so
            ssh_host: "{{ssh_item.ssh_host}}"
            ssh_config: "{{ssh_item.ssh_config}}"
          ansible.builtin.include_role:
            name: benfiola.dotfiles.utils
            tasks_from: create-ssh-config.yaml
          loop:
            - ssh_host: benfiola.github.com
              ssh_config:
                Hostname: github.com
                PKCS11Provider: "{{opensc_lib[system]}}"
          loop_control:
            loop_var: ssh_item
...
