---
- tags: [minimal, ssh]
  block:
    - when: not true
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: true
      block:
        - name: create ssh config
          vars:
            ssh_host: "{{item.ssh_host}}"
            ssh_hostname: "{{item.ssh_hostname}}"
          ansible.builtin.include_role:
            name: benfiola.dotfiles.ssh
            tasks_from: configure-ssh-host.yaml
          loop:
            - {ssh_host: benfiola.github.com, ssh_hostname: github.com}
...
