- name: install | install apt packages
  become: true
  apt: pkg=curl,git state=present

- name: install | set asdf_home fact
  set_fact: asdf_path={{user_home}}/.asdf

- name: install | set asdf_executable fact
  set_fact: asdf_executable={{asdf_path}}/bin/asdf

- name: install | clone asdf repository
  become: true
  become_user: "{{user_name}}"
  git: repo={{repo}} dest={{asdf_path}}
  vars:
    repo: https://github.com/asdf-vm/asdf.git

- name: install | update profile
  become: true
  become_user: "{{user_name}}"
  blockinfile: block={{block}} marker={{marker}} dest={{user_profile}}
  vars:
    block: "{{lookup('template', 'templates/profile.j2')}}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{role_name}}"
  