---
- name: "({{ username }}) Get user information"
  user:
    name: "{{ username }}"
  register: user

- name: "({{ user.name }}) Get shell profile path"
  vars:
    shell: "{{ user.shell | basename }}"
    shell_map:
      bash: "{{ user.home }}/.bashrc"
      zsh: "{{ user.home }}/.zshrc"
  set_fact:
    shell_profile: "{{ shell_map[shell] }}"

- name: Install apt packages
  become: true
  apt:
    state: present
    update_cache: true 
    pkg:
      - curl
      - git

- name: "({{ user.name }}) Clone asdf repositroy"
  become: true
  become_user: "{{ user.name }}"
  git: 
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ user.home }}/.asdf"

- name: "({{ user.name }}) Update shell profile"
  become: true
  become_user: "{{ user.name }}"
  blockinfile:
    dest: "{{ shell_profile }}"
    block: "{{ lookup('template', 'templates/asdf.zshrc.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ role_name }}"
  vars:
    asdf_path: "{{ user.home }}/.asdf"
  