# preset: nerd-font-symbols

# preset overrides
add_newline = false

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[character]
# preset overrides
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
# preset overrides
truncate_to_repo = false
truncation_length = 3
truncation_symbol = ".../"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[spack]
symbol = "🅢 "
