---
- tags: [minimal]
  block:
    - when: not (debian or archlinux or darwin)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: debian
      block:
        - name: apt add docker signing key
          become: true
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg

        - name: apt add docker repository
          become: true
          ansible.builtin.apt_repository:
            repo: "{{repositories[architecture]}}"
          vars:
            repositories:
              amd64: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{release}} stable
              arm64: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{release}} stable

        - name: apt install docker
          become: true
          ansible.builtin.apt:
            update_cache: true
            package:
              - containerd.io
              - docker-ce
              - docker-ce-cli
              - docker-compose-plugin

    - when: archlinux
      block:
        - name: pacman install docker
          become: true
          community.general.pacman:
            name:
              - docker
        
        - name: systemd enable docker service
          become: true
          ansible.builtin.systemd:
            name: docker
            state: started
            enabled: true

    - when: archlinux or debian
      block:
        - name: add docker group
          become: true
          ansible.builtin.group:
            name: docker

        - name: add user to docker group
          become: true
          ansible.builtin.user:
            name: "{{user.name}}"
            append: true
            groups: docker
      
    - when: darwin
      block:
        - name: brew cask install docker
          community.general.homebrew_cask:
            name: docker
            path: "{{brew_path}}"
...