- name: install | set facts
  set_fact:
    jbr_platform: "{{ansible_system | lower}}"
    jbr_architecture: "{{ansible_architecture | lower}}"
    jbr_major_version: "{{jbr_version.split('-')[0]}}"
    jbr_minor_version: "{{jbr_version.split('-')[1]}}"
  
- name: install | set architecture
  set_fact: jbr_architecture=aarch64
  when: jbr_architecture == 'arm64'

- block:    
    - name: install | unarchive url
      become: true
      unarchive: src={{url}} dest=/opt creates=/opt/jbr/bin/java remote_src=true mode=0755
      vars:
        url: https://cache-redirector.jetbrains.com/intellij-jbr/jbr-{{jbr_major_version}}-linux-aarch64-{{jbr_minor_version}}.tar.gz

    - name: install | set jbr location
      set_fact: jbr_path=/opt/jbr
  when: jbr_architecture == 'aarch64' and jbr_platform == 'linux'
