# installs '{{app}}' from dmg located at '{{url}}' to '/Applications/{{app}}'
# if '/Applications/{{app}}' exists, install is skipped
---
- name: check app exists
  ansible.builtin.stat:
    path: /Applications/{{app}}
  register: app_exists

- name: install app with dmg
  when: not app_exists.stat.exists
  block:
    - name: create temp directory
      temp_file:
        directory: true
      register: temp_path

    - name: unarchive dmg
      dmg_unarchive:
        src: "{{url}}"
        remote_src: true
        dest: "{{temp_path.path}}"

    - name: copy app
      ansible.builtin.copy:
        src: "{{temp_path.path}}/{{app}}/"
        dest: "/Applications/{{app}}"
        follow: true
        remote_src: true
