---
- block:
  - name: "Update apt-cache"
    apt: update_cache=yes
    become: true

  - name: "Install apt packages"
    become: true
    apt:
      state: present 
      pkg:
        - vim
        - zsh
        - xclip

  - name: "Create user: {{ user }}"
    become: true
    user:
      name: "{{ user }}"
      password: "{{ user | password_hash('sha512') }}"
      update_password : on_create
      state: present
  
  - name: "Configure user: {{ user }}"
    become: true
    user:
      name: "{{ user }}"
      state: present
      shell: "{{ shell }}"

  - name: "Create {{ path }} to add {{ user }} to sudoers"
    become: true
    lineinfile:
      path: "{{ path }}"
      line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
    vars:
      path: "/etc/sudoers.d/{{ user }}"

  - name: "Create {{ path }}"
    become: true
    become_user: "{{ user }}"
    file: 
      path: "{{ path }}"
      state: "directory"
      recurse: true
      owner: "{{ user }}"
    vars:
      path: "{{ user_home }}/source"

  - name: "Create {{ oh_my_zsh_path }}"
    become: true
    become_user: "{{ user }}"
    file: 
      path: "{{ oh_my_zsh_path }}"
      state: "directory"
      recurse: true
      owner: "{{ user }}"

  - name: "Clone {{ oh_my_zsh_url }} to {{ oh_my_zsh_path }}"
    become: true
    become_user: "{{ user }}"
    git: repo={{ oh_my_zsh_url }} dest={{ oh_my_zsh_path }}


  - name: "Copy {{ source }} to {{ destination }}"
    become: true
    become_user: "{{ user }}"
    copy: 
      src: "{{ source }}"
      dest: "{{ destination }}"
      owner: "{{ user }}"
    vars:
      source: "files/ben.zsh-theme"
      destination: "{{ oh_my_zsh_path }}/custom/themes/ben.zsh-theme"

  - name: "Create {{ shell_profile }}"
    become: true
    become_user: "{{ user }}"
    file: 
      path: "{{ shell_profile }}"
      state: touch 

  - name: "Add files to {{ shell_profile }}"
    become: true
    become_user: "{{ user }}"
    blockinfile:
      dest: "{{ shell_profile }}"
      block: "{{ lookup('file', '{{ item }}') }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ role_name }}:{{ item }}"
    with_items:
      - files/aliases.zshrc

  - name: "Add templates to {{ shell_profile }}"
    become: true
    become_user: "{{ user }}"
    blockinfile:
      dest: "{{ shell_profile }}"
      block: "{{ lookup('template', '{{ item }}') }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ role_name }}:{{ item }}"
    with_items:
      - templates/ohmyzsh.zshrc.j2

  - name: "Set facts"
    set_fact:
      user: "{{ user }}"
      user_home: "{{ user_home }}"
      shell: "{{ shell }}"
      shell_profile: "{{ shell_profile }}"
  vars:
    user: "benfiola"
    user_home: "/home/{{ user }}"
    shell: "/usr/bin/zsh"
    shell_profile: "{{ user_home }}/.zshrc"
    oh_my_zsh_url: "https://github.com/ohmyzsh/ohmyzsh.git"
    oh_my_zsh_path: "{{ user_home }}/.oh-my-zsh"
