---
- tags: [minimal, brew]
  block:
    - when: not darwin
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin
      block:
        - name: set brew path fact
          ansible.builtin.set_fact:
            brew_prefix: "{{prefix}}"
            brew_path: "{{prefix}}/bin"
          vars:
            prefixes:
              amd64: /usr/local
              arm64: /opt/homebrew
            prefix: "{{prefixes[architecture]}}"
          
        - name: install brew from url
          ansible.builtin.include_role: 
            role: benfiola.dotfiles.utils
            tasks_from: execute-url-as-script.yaml
          vars:        
            url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
            binary: "{{brew_path}}"
        
        - name: link zshrc file
          ansible.builtin.file:
            src: "{{dotfiles_path}}/roles/brew/files/profile.sh"
            path: "{{user_profiled_path}}/00-brew.sh"
            state: link
...
