---
- block:
  - name: "Update apt-cache"
    apt: update_cache=yes
    become: true

  - name: "Install apt packages"
    become: true
    apt:
      state: present 
      pkg:        
        - g++
        - gcc
        - make
        - cmake
