- name: install | set facts
  set_fact:
    tilt_platform: "{{ansible_system | lower}}"
    tilt_architecture: "{{ansible_architecture | lower}}"

- name: install | set architecture
  set_fact: tilt_architecture=arm64
  when: tilt_architecture == 'aarch64'

- name: install | set platform
  set_fact: tilt_platform=mac
  when: tilt_platform == 'darwin'

- name: install | download url
  become: true
  unarchive: src={{url}} dest=/usr/local/bin remote_src=true mode=a+x creates=/usr/local/bin/tilt
  vars:
    url: https://github.com/tilt-dev/tilt/releases/download/v{{tilt_version}}/tilt.{{tilt_version}}.{{tilt_platform}}.{{tilt_architecture}}.tar.gz
