---
- tags: [minimal, tanka]
  block:
    - when: not (darwin or archlinux or debian)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin or debian
      block:
        - name: brew install tanka
          community.general.homebrew:
            name: tanka
            path: "{{brew_path}}"
    
    - when: archlinux
      block:
        - name: pacman install tanka
          become: true
          community.general.pacman:
            name:
              - tanka
...