# creates a desktop file for "{{name}}"
- name: create {{name}}.desktop
  become: true
  ansible.builtin.template:
    src: desktop.j2
    dest: /usr/share/applications/{{name}}.desktop
    mode: '0644'
