---
- name: "({{ username }}) Get user information"
  user:
    name: "{{ username }}"
  register: user

- name: "Install apt packages"
  become: true
  apt:
    state: present 
    pkg:
      - git
    update_cache: true
  
- name: "({{ user.name }}) Setting global git configuration"
  become: true
  become_user: "{{ user.name }}"
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - name: user.name
      value: "{{ git_config_user_name }}"
    - name: user.email
      value: "{{ git_config_user_email }}"
