---
- tags: [minimal, git]
  block:
    - when: not (true)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: true
      vars:
        git_config:
          user.name: "Ben Fiola"
          user.email: benfiola@gmail.com
          user.signingkey: 9431F68902C615C7
          commit.gpgsign: true
          init.defaultbranch: main
      block:
        - name: create git config
          ansible.builtin.include_role:
            name: benfiola.dotfiles.utils
            tasks_from: create-git-config.yaml
          loop:
            - "{{source_path}}/benfiola.github.com/"
          loop_control:
            loop_var: directory
...
