---
- tags: [minimal, git]
  block:
    - when: not (true)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: true
      block:
        - name: create git config
          vars:
            directory: "{{git_config_item.directory}}"
            data: "{{git_config_item.data}}"
          ansible.builtin.include_role:
            name: benfiola.dotfiles.utils
            tasks_from: create-git-config.yaml
          loop:
            - directory: "{{source_path}}/benfiola.github.com/"
              data: 
                user.name: "Ben Fiola"
                user.email: benfiola@gmail.com
                user.signingkey: 9431F68902C615C7
                commit.gpgsign: true
          loop_control:
            label: "{{git_config_item.directory}}"
            loop_var: git_config_item
...
