---
- tags: [optional, "{{role_name}}"]
  block:
    - when: not (darwin or archlinux)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin
      block:
        - name: brew cask install steam
          community.general.homebrew_cask:
            name: steam
            path: "{{brew_path}}"
    
    - when: archlinux
      block:
        - name: pacman install steam
          become: true
          community.general.pacman:
            name:
              - steam
...