---
- tags: [minimal, yubikey]
  block:
    - when: not (darwin or archlinux)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin
      block:
        - name: brew install ykman
          community.general.homebrew:
            name: 
              - ykman
              - libfido2
            path: "{{brew_path}}"
    
    - when: archlinux
      block:
        - name: pacman install ykman
          become: true
          community.general.pacman:
            name:
              - yubikey-manager
              - libfido2
...
