---
- tags: [minimal, yubikey]
  block:
    - when: not (darwin or archlinux)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin
      block:
        - name: brew install yubikey dependencies
          community.general.homebrew:
            name: 
              - gnupg
              - ykman
            path: "{{brew_path}}"
        
        - name: brew install yubikey dependencies
          community.general.homebrew_cask:
            name: 
              - homebrew/cask/opensc
            path: "{{brew_path}}"
    
    - when: archlinux
      block:
        - name: pacman install yubikey dependencies
          become: true
          community.general.pacman:
            name:
              - ccid
              - gnupg
              - opensc
              - pcsclite
              - yubikey-manager
    
        - name: start pcscd service
          become: true
          ansible.builtin.systemd:
            name: pcscd
            state: started
            enabled: true
...