---
- tags: [minimal]
  block:
    - when: not true
      block:
        - name: unimplemented
          empty: {}
    
    - when: true
      block:
        - name: link zshrc file
          ansible.builtin.file:
            src: "{{dotfiles_path}}/roles/source/files/zshrc.sh"
            path: "{{user_profiled_path}}/00-source.sh"
            state: link

        - name: link src bin file
          ansible.builtin.file:
            src: "{{dotfiles_path}}/roles/source/files/src.sh"
            path: "{{user_bin_path}}/src"
            state: link
...