---
- tags: [minimal, sops]
  block:
    - when: not (darwin or archlinux or debian)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin or debian
      block:
        - name: brew install sops
          community.general.homebrew:
            name: 
              - gnupg
              - sops
            path: "{{brew_path}}"
    
    - when: archlinux
      block:
        - name: pacman install sops
          become: true
          community.general.pacman:
            name:
              - gnupg
              - sops
...
