---
- block:
  - name: "Create {{ appimaged_directory }}"
    file: path={{ appimaged_directory }} state=directory recurse=true owner={{ user }} mode=777
    become: true

  - name: Download {{ appimaged_url }} to {{ appimaged_path }}
    get_url: url={{ appimaged_url }} dest={{ appimaged_path }} mode=755
    become: true
    become_user: "{{ user }}"  

  - name: Install {{ appimaged_path }}
    command: 
      cmd: "{{ appimaged_path }}"

  - name: Register uid of {{ user }}
    command: id -u {{ user }}
    register: uid

  - name: "Start appimaged.service"
    systemd: name=appimaged state=started enabled=yes scope=user
    environment:
      XDG_RUNTIME_DIR: /run/user/{{uid.stdout}}
  vars:
    appimaged_directory: "/opt/appimaged"
    appimaged_url: "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-640-x86_64.AppImage"
    appimaged_path: "{{ appimaged_directory }}/appimaged.AppImage"