- name: install | set facts
  set_fact:
    gcloud_os_family: "{{ansible_os_family | lower}}"

- name: install | add gpg keys
  become: true
  apt_key: url={{url}} state=present
  vars:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
  register: gcloud_apt_keys
  when: gcloud_os_family == 'debian'
  
- name: install | add apt repository
  become: true
  apt_repository: repo={{repo}} state=present
  vars:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
  register: gcloud_apt_repository
  when: gcloud_os_family == 'debian'

- name: install | update apt cache
  become: true
  apt: update_cache=true
  when: gcloud_os_family == 'debian' and (gcloud_apt_keys.changed or gcloud_apt_repository.changed)

- name: install | install apt packages
  become: true
  apt: pkg=google-cloud-sdk state=present
  when: gcloud_os_family == 'debian'
