---
- block:
  - name: "Create {{ unity_hub_editors_path }}"
    file: path={{ unity_hub_editors_path }} state=directory recurse=true owner={{ user }} mode=777
    become: true

  - name: Download {{ unity_hub_url }} to {{ unity_hub_path }}
    get_url: url={{ unity_hub_url }} dest={{ unity_hub_path }} mode=755
    become: true

  - name: Set facts
    set_fact:
      unity_hub_path: "{{ unity_hub_path }}"
      unity_hub_editors_path: "{{ unity_hub_editors_path }}"
  vars:
    unity_hub_editors_path: "/opt/unity_hub/editors"
    unity_hub_path: "/opt/Unity Hub.AppImage"
    unity_hub_url: "https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage"
