---
- name: Update apt-cache
  apt: update_cache=yes
  become: true

- name: Install apt packages
  become: true
  apt:
    state: present 
    pkg:
      - make 
      - build-essential 
      - libssl-dev 
      - zlib1g-dev 
      - libbz2-dev 
      - libreadline-dev 
      - libsqlite3-dev 
      - wget 
      - curl 
      - llvm 
      - libncurses5-dev 
      - xz-utils 
      - tk-dev 
      - libxml2-dev 
      - libxmlsec1-dev 
      - libffi-dev 
      - liblzma-dev

- name: "Create {{ path }}"
  file: path={{ path }} state=directory recurse=true owner={{ user }}
  become: true
  become_user: "{{ user }}"
  vars:
    path: "{{ pyenv_path }}"

- name: "Clone {{ source }} to {{ destination }}"
  git: repo={{ source }} dest={{ destination }}
  become: true
  become_user: "{{ user }}"
  vars:
    source: https://github.com/pyenv/pyenv.git
    destination: "{{ pyenv_path }}"

- name: "Clone {{ source }} to {{ destination }}"
  git: repo={{ source }} dest={{ destination }}
  become: true
  become_user: "{{ user }}"
  vars:
    source: https://github.com/pyenv/pyenv-virtualenv
    destination: "{{ pyenv_path }}/plugins/pyenv-virtualenv"

- name: "Add {{ file }} to {{ shell_profile }}"
  blockinfile:
    dest: "{{ shell_profile }}"
    block: "{{ lookup('file', '{{ file }}') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ role_name }}:{{ file }}"
  vars:
    file: files/pyenv.zshrc

- name: Set facts
  set_fact:
    pyenv_path: "{{ pyenv_path }}"
  