- name: instal | set facts
  set_fact: webstorm_ide_path=/opt/webstorm

- name: install | create extract directory
  become: true
  file: path={{webstorm_ide_path}} state=directory recurse=true mode=0755

- name: install | download url
  become: true
  unarchive: src={{url}} remote_src=true dest={{webstorm_ide_path}} creates={{webstorm_ide_path}}/bin/webstorm.sh extra_opts=--strip-components=1 mode=0755
  vars:
    url: https://download.jetbrains.com/webstorm/WebStorm-{{webstorm_version}}.tar.gz

- name: install | set java path
  set_fact: webstorm_java_path={{webstorm_ide_path}}/jbr
  when: jbr_path is undefined

- name: install | set java path
  set_fact: webstorm_java_path={{jbr_path}}
  when: jbr_path is not undefined

- name: install | create launch script
  become: true
  copy: content={{content}} dest={{webstorm_ide_path}}/bin/launch.sh mode=0755
  vars:
    content: "{{lookup('template', 'templates/launch.sh.j2')}}"

- name: install | create desktop launcher
  copy: content={{content}} dest={{user_home}}/.local/share/applications/webstorm.desktop mode=0755
  vars:
    content: "{{lookup('template', 'templates/desktop.j2')}}"