---
- name: "Get kernel version"
  command: uname -r
  register: kernel_version

- name: "Update apt-cache"
  apt: update_cache=yes
  become: true

- name: "Install apt packages"
  become: true
  apt:
    state: present 
    pkg:
      - build-essential
      - dkms
      - linux-headers-{{kernel_version.stdout}}

- name: "Create {{ path }}"
  file: path={{ path }} recurse=true state=directory
  become: true
  vars:
    path: "{{ vbox_guest_additions_mount_point }}"

- name: "Mount {{ source }} to {{ target }}"
  become: true
  mount:
    src: "{{ source }}"
    path: "{{ target }}"
    state: mounted
    fstype: iso9660
  vars:
    source: "{{ vbox_guest_additions_device }}"
    target: "{{ vbox_guest_additions_mount_point }}"

- name: "Run {{ command }}"
  become: true
  expect:
    command: "{{ command }}"
    responses: {}
    timeout: null
  register: command_result
  failed_when: "command_result.stderr | length > 0"
  ignore_errors: true
  vars:
    command: "{{ vbox_guest_additions_mount_point }}/VBoxLinuxAdditions.run"

- name: "Ensuring guest additions modules are found via {{ command }}"
  become: true
  command:
    cmd: "{{ command }}"
  vars:
    command: "modinfo vboxsf"
  
- name: "Unmount {{ source }}"
  become: true
  mount:
    path: "{{ source }}"
    state: unmounted
  vars:
    source: "{{ vbox_guest_additions_mount_point }}"

- name: "Remove {{ path }}"
  file: path={{ path }} state=absent
  become: true
  vars:
    path: "{{ vbox_guest_additions_mount_point }}"
