---
- tags: [graphical, iterm2]
  block:
    - when: not darwin
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: darwin
      block:
        - name: brew install homebrew/cask/iterm2
          community.general.homebrew_cask:
            name: homebrew/cask/iterm2
            path: "{{brew_path}}"
          
        - name: run configuration commands
          ansible.builtin.command:
            cmd: "{{dotfiles_path}}/roles/iterm2/files/config.sh"
          changed_when: false
...