---
- name: "({{ username }}) Get user information"
  become: true
  user:
    name: "{{ username }}"
  register: user

- name: "({{ user.name }}) Get asdf executable"
  set_fact:
    asdf_executable: "{{ user.home }}/.asdf/bin/asdf"

- name: "({{ user.name }}) Check if asdf executable exists"
  become: true
  become_user: "{{ user.name }}"
  stat:
    path: "{{ asdf_executable }}"
  register: asdf_executable_stat

- fail:
    msg: "asdf executabhle not found"
  when: 'not asdf_executable_stat.stat.exists'

- name: "({{ user.name }}) Get asdf plugin list"
  become: true
  become_user: "{{ user.name }}"
  command: 
    cmd: "{{ asdf_executable }} plugin list"
  register: asdf_plugin_list
  failed_when: asdf_plugin_list.rc != 0 and 'No plugins installed' not in asdf_plugin_list.stderr

- name: ({{ user.name }}) Install plugin
  become: true
  become_user: "{{ user.name }}"
  command:
    cmd: "{{ asdf_executable }} plugin add tilt"
  when: "'tilt' not in asdf_plugin_list.stdout"
  