- name: instal | set facts
  set_fact: clion_ide_path=/opt/clion

- name: install | create extract directory
  become: true
  file: path={{clion_ide_path}} state=directory recurse=true mode=0755

- name: install | download url
  become: true
  unarchive: src={{url}} remote_src=true dest={{clion_ide_path}} creates={{clion_ide_path}}/bin/clion.sh extra_opts=--strip-components=1 mode=0755
  vars:
    url: https://download.jetbrains.com/cpp/CLion-{{clion_version}}.tar.gz

- name: install | set java path
  set_fact: clion_java_path={{clion_ide_path}}/jbr
  when: jbr_path is undefined

- name: install | set java path
  set_fact: clion_java_path={{jbr_path}}
  when: jbr_path is not undefined

- name: install | create launch script
  become: true
  copy: content={{content}} dest={{clion_ide_path}}/bin/launch.sh mode=0755
  vars:
    content: "{{lookup('template', 'templates/launch.sh.j2')}}"

- name: install | create desktop launcher
  copy: content={{content}} dest={{user_home}}/.local/share/applications/clion.desktop mode=0755
  vars:
    content: "{{lookup('template', 'templates/desktop.j2')}}"