---
- tags: [minimal, "{{role_name}}"]
  block:
    - when: not (debian or archlinux)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: debian
      block:
      - name: apt install snapd
        become: true
        ansible.builtin.apt:
          package:
            - snapd
    
    - when: archlinux
      block:
        - name: pacman aur install snapd
          ansible.builtin.include_role: 
            name: benfiola.dotfiles.utils
            tasks_from: install-pacman-aur.yaml
          vars:
            url: https://aur.archlinux.org/snapd.git
            package: snapd
        
        - name: enable snapd socket
          become: true
          ansible.builtin.systemd:
            name: snapd.socket
            state: started
            enabled: true
        
        - name: symlink snapd to /snapd
          become: true
          ansible.builtin.file:
            src: /var/lib/snapd/snap
            path: /snap
            state: link
...