---
- hosts: 127.0.0.1
  connection: local
  roles:
    - appimaged
    - asdf
    - asdf-golang
    - asdf-kind
    - asdf-kubectl
    - asdf-nodejs
    - asdf-python
    - asdf-sops
    - asdf-tilt
    - c++
    - clion
    - ctlptl
    - docker
    - git
    - goland
    - mdns
    - pycharm
    - qemu
    - unity_hub
    - user
    - vs_code
