---
- name: install | set facts
  set_fact:
    docker_os_family: "{{ansible_os_family | lower}}"
    docker_architecture: "{{ansible_architecture | lower}}"

- name: install | set architecture
  set_fact: docker_architecture=arm64
  when: docker_architecture == 'aarch64'

- name: install | install apt packages
  become: true
  apt: pkg=gpg state=present

- name: install | add gpg keys
  become: true
  apt_key: url={{url}} state=present
  vars:
    url: https://download.docker.com/linux/ubuntu/gpg 
  register: docker_apt_keys
  when: docker_os_family == 'debian'
  
- name: install | add apt repository
  become: true
  apt_repository: repo={{repo}} state=present
  vars:
    repo: deb [arch={{docker_architecture}}] https://download.docker.com/linux/ubuntu bionic stable
  register: docker_apt_repository
  when: docker_os_family == 'debian'

- name: install | update apt cache
  become: true
  apt: update_cache=true
  when: docker_os_family == 'debian' and (docker_apt_keys.changed or docker_apt_repository.changed)

- name: install | install apt packages
  become: true
  apt: pkg=docker-ce state=present
  when: docker_os_family == 'debian'

- name: install | create system group
  become: true
  group: name=docker state=present

- name: install | add user to system group
  become: true
  user: name={{user_name}} groups=docker append=true

- name: install | start service
  become: true
  systemd: name=docker state=started enabled=true
  