---
- name: "Add apt repository GPG keys"
  become: true
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg 
    state: present
  
- name: "Add apt repository"
  become: true
  apt_repository: 
    state: present
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

- name: "Install apt packages"
  become: true
  apt:
    update_cache: true
    state: present 
    pkg:
      - docker-ce

- name: Add group
  become: true
  group:
    name: docker
    state: present

- name: Add user to group
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: true

- name: "Start service"
  become: true
  systemd: 
    name: docker
    state: started
    enabled: true
  