- name: install | install apt packages
  become: true
  apt: pkg=imwheel state=present

- name: install | set facts
  set_fact:
    imwheel_service_path: "{{user_home}}/.config/systemd/user/imwheel.service"
  
- name: install | create user systemd folder
  become: true
  become_user: "{{user_name}}"
  file: path={{path}} state=directory recurse=true
  vars:
    path: "{{imwheel_service_path | dirname}}"
  
- name: install | create service
  copy: dest={{imwheel_service_path}} content={{content}}
  vars:
    content: "{{ lookup('template', 'templates/service.j2') }}"
  notify:
  - handlers | restart imwheel service

- name: install | start service
  become: true
  become_user: "{{user_name}}"
  systemd: name=imwheel state=started enabled=true scope=user
