asdf_ctlptl_version: "0.5.5"
asdf_direnv_version: "2.28.0"
asdf_gcloud_version: "347.0.0"
asdf_golang_version: "1.16.5"
asdf_java_version: "openjdk-16"
asdf_jb_version: "0.4.0"
asdf_jsonnet_version: "0.17.0"
asdf_kind_version: "0.11.1"
asdf_kubebuilder_version: "3.1.0"
asdf_kubectl_version: "1.21.2"
asdf_nodejs_version: "16.4.0"
asdf_python_version: "3.9.6"
asdf_sops_version: "3.7.1"
asdf_tanka_version: "0.16.0"
asdf_tilt_version: "0.21.0"
user_name: "{{ansible_user_id}}"
user_shell: "zsh"
git_config_user_name: "Ben Fiola"
git_config_user_email: "benfiola@gmail.com"