---
- name: "Create {{ path }}"
  file: path={{ path }} state=directory owner={{ user }}
  become: true
  become_user: "{{ user }}"
  vars:
    path: "{{ nodenv_path }}"

- name: "Clone {{ source }} to {{ destination }}"
  git: repo={{ source }} dest={{ destination }}
  become: true
  become_user: "{{ user }}"
  vars:
    source: https://github.com/nodenv/nodenv.git
    destination: "{{ nodenv_path }}"

- name: "Clone {{ source }} to {{ destination }}"
  git: repo={{ source }} dest={{ destination }}
  become: true
  become_user: "{{ user }}"
  vars:
    source: https://github.com/nodenv/node-build.git
    destination: "{{ nodenv_path }}/plugins/node-build"

- name: "Add {{ file }} to {{ shell_profile }}"
  blockinfile:
    dest: "{{ shell_profile }}"
    block: "{{ lookup('file', '{{ file }}') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ role_name }}:{{ file }}"
  vars:
    file: files/nodenv.zshrc

- name: "Set facts"
  set_fact:
    nodenv_path: "{{ nodenv_path }}"
