---
- tags: [minimal]
  block:
    - when: not (darwin or archlinux or debian)
      block:
        - name: unimplemented
          empty: {}
    
    - when: debian
      block:
        - name: apt install gnupg2
          become: true
          ansible.builtin.apt:
            package:
              - gnupg2

    - when: darwin
      block:
        - name: brew install gnupg
          community.general.homebrew:
            name: gnupg
            path: "{{brew_path}}"
    
    - when: archlinux
      block:
        - name: pacman install gnupg
          become: true
          community.general.pacman:
            name:
              - gnupg
...