---
- tags: [optional, bitwarden]
  block:
    - when: not (linux or darwin)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: linux
      block:
        - name: flatpak install bitwarden
          become: true
          community.general.flatpak:
            name: com.bitwarden.desktop

    - when: darwin
      block:
        - name: brew install homebrew/cask/bitwarden
          community.general.homebrew_cask:
            name: homebrew/cask/bitwarden
            path: "{{brew_path}}"
...
