---
- tags: [optional, "{{role_name}}"]
  block:
    - when: not archlinux
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}
    
    - when: archlinux
      block:
      - name: pacman install lutris
        become: true
        community.general.pacman:
          name:
            - lutris
...